name       : mate-icon-theme
version    : 1.26.0
release    : 13
source     :
    - https://github.com/mate-desktop/mate-icon-theme/releases/download/v1.26.0/mate-icon-theme-1.26.0.tar.xz : 41f50436d57f425e54fd9557541be77fb291e03aacd55f7991c042e84a290a5a
license    : CC-BY-SA-3.0
component  : desktop.mate
summary    : MATE Desktop Icon Theme
description: |
    The standard icon theme for the MATE Desktop
builddeps  :
    - pkgconfig(icon-naming-utils)
setup      : |
    %configure --enable-icon-mapping
build      : |
    %make
install    : |
    %make_install
