name       : mate-icon-theme
version    : 1.16.0
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-icon-theme-1.16.0.tar.xz : edec67867b26974ef286cd85e968efee3ee5ea4d232b86b48ee6c47085e08dfe
license    : CC-BY-SA-3.0
component  : desktop.mate
summary    : MATE Desktop Icon Theme
description: |
    The standard icon theme for the MATE Desktop
builddeps  :
    - pkgconfig(icon-naming-utils)
setup      : |
    %configure --enable-icon-mapping
build      : |
    %make
install    : |
    %make_install
