name       : mate-icon-theme
version    : 1.22.0
release    : 9
source     :
    - https://github.com/mate-desktop//mate-icon-theme/archive/v1.22.0.tar.gz : d630cedbe429ca0c5c551a04c43e2bee4a9cf5ae864608d7d8ef331af5786f24
license    : CC-BY-SA-3.0
component  : desktop.mate
summary    : MATE Desktop Icon Theme
description: |
    The standard icon theme for the MATE Desktop
builddeps  :
    - pkgconfig(icon-naming-utils)
    - mate-common
setup      : |
    %autogen --enable-icon-mapping
build      : |
    %make
install    : |
    %make_install
