name       : mate-icon-theme
version    : 1.18.2
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-icon-theme-1.18.2.tar.xz : 9091373f9672634b5bc09344d4819df717e48ac55b6a057f21faa83f47a4236a
license    : CC-BY-SA-3.0
component  : desktop.mate
summary    : MATE Desktop Icon Theme
description: |
    The standard icon theme for the MATE Desktop
builddeps  :
    - pkgconfig(icon-naming-utils)
setup      : |
    %configure --enable-icon-mapping
build      : |
    %make
install    : |
    %make_install
