name       : mate-icon-theme
version    : 1.22.2
release    : 11
source     :
    - https://github.com/mate-desktop/mate-icon-theme/archive/v1.22.2.tar.gz : b224245fb9851dfbea14eebf3196f290d6d0375306bca06945459bfcad8cb25a
license    : CC-BY-SA-3.0
component  : desktop.mate
summary    : MATE Desktop Icon Theme
description: |
    The standard icon theme for the MATE Desktop
builddeps  :
    - pkgconfig(icon-naming-utils)
    - mate-common
setup      : |
    %autogen --enable-icon-mapping
build      : |
    %make
install    : |
    %make_install
