name       : mate-icon-theme
version    : 1.20.3
release    : 8
source     :
    - https://github.com/mate-desktop/mate-icon-theme/archive/v1.20.3.tar.gz : c5a1b5a2f4d024a91675e10cfec9e43d12b0b2f78cf8888bc25257aa44c365b0
license    : CC-BY-SA-3.0
component  : desktop.mate
summary    : MATE Desktop Icon Theme
description: |
    The standard icon theme for the MATE Desktop
builddeps  :
    - pkgconfig(icon-naming-utils)
    - mate-common
setup      : |
    %autogen --enable-icon-mapping
build      : |
    %make
install    : |
    %make_install
