name       : mate-icon-theme
version    : 1.20.2
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-icon-theme-1.20.2.tar.xz : d69acb308c563399ac560e60783c22a7808e81967e036d48c5df44071a006cda
license    : CC-BY-SA-3.0
component  : desktop.mate
summary    : MATE Desktop Icon Theme
description: |
    The standard icon theme for the MATE Desktop
builddeps  :
    - pkgconfig(icon-naming-utils)
setup      : |
    %configure --enable-icon-mapping
build      : |
    %make
install    : |
    %make_install
