name       : mate-icon-theme
version    : 1.22.1
release    : 10
source     :
    - https://github.com/mate-desktop/mate-icon-theme/archive/v1.22.1.tar.gz : 48427dfd882c92d6a4791ea3977d26af60c63ee792da03f38c0ff3aaaa2e2e20
license    : CC-BY-SA-3.0
component  : desktop.mate
summary    : MATE Desktop Icon Theme
description: |
    The standard icon theme for the MATE Desktop
builddeps  :
    - pkgconfig(icon-naming-utils)
    - mate-common
setup      : |
    %autogen --enable-icon-mapping
build      : |
    %make
install    : |
    %make_install
