name       : mate-icon-theme
version    : 1.24.0
release    : 12
source     :
    - https://github.com/mate-desktop/mate-icon-theme/releases/download/v1.24.0/mate-icon-theme-1.24.0.tar.xz : ca9e5387439fcf7eed53eb33f10a6d3ae51b4d96af525eed6f8cf31d83f95428
license    : CC-BY-SA-3.0
component  : desktop.mate
summary    : MATE Desktop Icon Theme
description: |
    The standard icon theme for the MATE Desktop
builddeps  :
    - pkgconfig(icon-naming-utils)
setup      : |
    %configure --enable-icon-mapping
build      : |
    %make
install    : |
    %make_install
